#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
if [ "$#" -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]
	PATH_TO_FILE = $1
	IP = $2
	USERNAME = $3
	PATH_TO_SSH_KEY = $4
then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"