#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine 
apt-get -y update
apt-get -y install nginx
service nginx start
# ufw allow 'Nginx HTTP'
# chmod -R 755 /var/www/html
echo "Hello World!" > /var/www/html/index.html
service nginx restart
