#!/usr/bin/env bash
# Bash script that configures Nginx to add a custom header to its HTTP response

sudo apt-get -y update
sudo apt-get -y install nginx

# hn=$HOSTNAME
string="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$string/" /etc/nginx/nginx.conf
# echo "more_set_headers \"X-Served-By: $hn\";" | sudo tee -a /etc/nginx/nginx.conf

sudo service nginx start
