#!/usr/bin/env bash
# this is comment
WEB1_HOST="449516-web-01"
WEB2_HOST="449516-web-02"
WEB1_IP="54.90.1.129"
WEB2_IP="18.208.119.233"

sudo apt update -y
sudo apt upgrade -y

sudo apt install haproxy -y

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

sudo cat > /etc/haproxy/haproxy.cfg <<EOF

frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server $WEB1_HOST $WEB1_IP:80 check
   server $WEB2_HOST $WEB2_IP:80 check
EOF

# Enable and start HAproxy service
sudo service haproxy restart
