#!/usr/bin/env bash
# Create the PID file
echo $$ > /var/run/myscript.pid

# Define a function to handle SIGTERM signals
function sigterm_handler {
    echo "I hate the kill command"
    exit 0
}

# Define a function to handle SIGINT signals
function sigint_handler {
    echo "Y U no love me?!"
}

# Define a function to handle SIGQUIT signals
function sigquit_handler {
    rm /var/run/myscript.pid
    exit 0
}

# Register the signal handlers
trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

# Display "To infinity and beyond" indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 2
done
