#!/usr/bin/env bash
# Define the path to the PID file
pid_file="/var/run/my_process.pid"

script_file="/tmp/my_process"

function start_process {
	if [ -f "$pid_file" ] && kill -0 "$(cat "$pid_file")" 2>/dev/null; then
        echo "manage_my_process is already running"
        exit 1
    fi

    echo "manage_my_process started"
    while true; do
        echo "I am alive!" >> "$script_file"
        sleep 2
    done &
    echo $! > "$pid_file"
}

function stop_process {
	if [ ! -f "$pid_file" ] || ! kill -0 "$(cat "$pid_file")" 2>/dev/null; then
        echo "manage_my_process is not running"
        exit 1
    fi

    echo "manage_my_process stopped"
    kill "$(cat "$pid_file")"
    rm "$pid_file"
}

function restart_process {
    echo "manage_my_process restarted"
    stop_process
    start_process
}

case "$1" in
    start)
        start_process;;
    stop)
        stop_process;;
    restart)
        restart_process;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1;;
esac

exit 0

