#!/usr/bin/env bash
# Bash script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process
ps -fu "$(whoami)" | grep -w bash | grep -v grep | awk '{print $1, $11}'
